version: '3.9' 

services:
  main:
    build:
      dockerfile: Dockerfile
      context: ./
    command: yarn start:prod
    volumes:
      - .:/usr/src/app
    env_file:
    - .env.production
    ports:
      - 80:80
