name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CodeBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checking node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:ci

      - name: Unit Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:ci

      - name: Run production build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
